config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'
  resources :places do
    resources :comments, only: :create
    resources :photos, only: [:create, :show]
  end
  resources :users, only: :show 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  RATINGS = {
    '★☆☆☆☆': '1_star',
    '★★☆☆☆': '2_stars',
    '★★★☆☆': '3_stars',
    '★★★★☆': '4_stars',
    '★★★★★': '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver_now
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  belongs_to :place

  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :photos
  geocoded_by :address
  after_validation :geocode
  
  validates :name, presence: true, length: { maximum: 50, minimum: 3 }
  validates :address, presence: true, length: { maximum: 240, minimum: 3 }
  validates :description, presence: true, length: { maximum: 500, minimum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :places
  has_many :comments
  has_many :photos
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params.merge(user: current_user))
    #raise "debug"
    redirect_to place_path(@place)
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @places = Place.paginate(page: params[:page], per_page: 10)
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end  

  def edit
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render plain: 'forbidden', status: :forbidden
    end
  end

  def update
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'forbidden', status: :forbidden
    end

    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
     if @place.user != current_user
      return render plain: 'forbidden', status: :forbidden
    end

    @place.destroy
    redirect_to root_path
  end


  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snackopolis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
<%#  <a class="navbar-brand" href="#">Snackopolis</a> %>
  <%= link_to 'Snackopolis', root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
<%#        <a class="nav-link" href="#">Link</a> %>
        <%= link_to new_place_path, class: 'nav-link' do %>
          <i class="fa fa-plus-circle"></i>
          new place
        <% end %>

      </li>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'my profile', user_path(current_user), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'sign in', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'sign up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb

<div class="booyah-box col-10 offset-1">
  <h1>edit your place </h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'update', class: 'btn btn-info' %>
  <% end %>
</div>

app/views/places/index.html.erb

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag 'slider1test.jpg', class: 'd-block w-100' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>find the best sandwich places</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider2test.jpg', class: 'd-block w-100' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>quench your thirst</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider3.jpg', class: 'd-block w-100' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>looking for hotdogs? you're one click away.</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider4.jpg', class: 'd-block w-100' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>is it technically a sandwich? maybe.</h3>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">next</span>
  </a>
</div>

<% @places.each do |place| %>  
  <h1><% place.name %></h1>
  <div class="booyah-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p><br />

    <% if place.user.present? %>
      <small><%= place.user.email %></small>
    <% end %>

<% if place.comments.present? %>
  <div class="col-12">
  <blockquote>
    <% if place.comments.last.humanized_rating.present? %>
      <b><%= place.comments.last.humanized_rating %></b> -
    <% end %>
    <%= place.comments.last.message %>
    <small><%= place.comments.last.user.email %></small>
  </blockquote>
  </div>
<% end %>    
</div>

<% end %>

<%= will_paginate @places %><br />


app/views/places/new.html.erb

<div class="booyah-box col-10 offset-1">
  <h1>enter your place details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'create', class: 'btn btn-info' %>
  <% end %>
</div>

app/views/places/show.html.erb

<div class="booyah-box col-10 offset-1">
  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i>
  <br/><br/>
  <p><%= @place.description %></p>


<%- #<style>
  #html, body {
  #  height: 100%;
  #  margin: 0;
  #  padding: 0;
  #}
  
#</style> 
#lesson 30 says to delete everything here and paste it into the master.scss file, but then only shows one line copied over???%>


<% if @place.latitude.present? && @place.longitude.present? %>


  <script>

    function initMap() {
      var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: myLatLng
      });

       var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
    }
  </script>

  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBg5-JStRYF6PyAWjsW0hqdEWnM2vPUzmk&callback=initMap">
  </script>

  <div id="map"></div>

<% end %>

<br />


  <div class="float-right">
    <% if current_user && current_user == @place.user %>
      <%= link_to 'edit', edit_place_path(@place), class: 'btn btn-info' %>
      <%= link_to 'destroy', place_path(@place), method: :delete, data: {confirm: 'are you sure you want to delete this place?'},class: 'btn btn-danger' %>
    <% end %>
  </div>
<div class="clear"></div>
</div>




<!-- Button trigger modal -->
<button type="button" class="btn btn-info btn-lg float-right" data-toggle="modal" data-target="#myModal">
  add a comment
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">send your compliments to the chef</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="close">
          <span aria-hidden="true"> × </span>
        </button>
        
      </div>
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :message %>
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">close</button>
          <%= f.submit "submit", type: 'submit', class: 'btn btn-info' %>
        </div>
      <% end %>
        
      </div>
    </div>
  </div>
  
<!-- Button trigger modal -->
<button type="button" class="btn btn-info btn-lg float-right" data-toggle="modal" data-target="#myModal2">
  add a photo
</button>


<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">show us what you got!</h4>
      </div>
      <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :picture %>
          <%= f.input :caption %>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">close</button>
            <%= f.submit "submit", type: 'submit', class: 'btn btn-info' %>
          </div>
        </div>
      <% end %>    
    </div>
  </div>
  <div class="clear"></div>
</div>
<div class="clear"></div>



  

<!-- </div> -->

<h1>comments</h1>

<div class="row">
  <% @place.comments.each do |comment| %>
    <div class="col-12 col-sm-6">
      <blockquote>
        <% if comment.humanized_rating.present? %>
        <b><%= comment.humanized_rating %></b> -
      <% end %>
        <%= comment.message %>
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
  <% end %>
</div>

<br />

<h1>pictures</h1>

<div class="row">
  <% @place.photos.each do |photo| %>
    <div class="col-12 col-sm-6">
      <blockquote>
        <% photo.caption.present? %>
        
          <%= image_tag photo.picture.url, :height => "150px" %>
        
        <small><%= photo.caption %></small>
      </blockquote>
    </div>
  <% end %>
</div>

<br />

app/views/users/show.html.erb

<div class= "booyah-box">
  <div class="row">
    <div class="col-4">
      <%= image_tag 'user.png' %>
    </div>

    <div class="col-8">
      <h1><%= @user.email %></h1>
      <h3>member since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
      <h4>total comments: <%= @user.comments.count %></h4>
      <h4>five-star reviews: <%= @user.comments.where(rating: '5_stars').count %></h4>
    </div>
  </div>
  <div class="clear"></div>
</div>

<br /><br />
<h5 class="text-center">my comments</h5>
<br /><br />
<div class="row">
  <% @user.comments.each do |comment| %>
    <div class="col-12 col-sm-6">
      <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
      <blockquote>
        <% if comment.humanized_rating.present? %>
          <b><%= comment.humanized_rating %></b> -
        <% end %>
        <%= comment.message %>
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
  <% end %>
</div>

<div class="clear"></div>
<br /><br />
<h5 class="text-center">my places</h5>
<br /><br />

<% @user.places.each do |place| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p><br />

    <% if place.user.present? %>
      <small><%= place.user.email %></small>
    <% end %>

<% if place.comments.present? %>
  <div class="col-12">
  <blockquote>
    <% if place.comments.last.humanized_rating.present? %>
      <b><%= place.comments.last.humanized_rating %></b> -
    <% end %>
    <%= place.comments.last.message %>
    <small><%= place.comments.last.user.email %></small>
  </blockquote>
  </div>
<% end %>    
</div>
<% end %>